"""Gemini-powered natural-language explanation of saliency maps."""
from __future__ import annotations

import base64
import io
import os
from dataclasses import dataclass

from PIL import Image

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
GEMINI_MODEL = os.environ.get("GEMINI_MODEL", "gemini-1.5-flash")

_genai = None
_model = None


def _build_prompt(predicted_class: str, confidence: float) -> str:
    return f"""You are an expert neurologist. You are tasked with explaining a saliency map of a brain tumor MRI scan.
The saliency map was generated by a deep learning model that was trained to classify brain tumors as either glioma, meningioma, pituitary or no tumor.

The saliency map highlights the regions of the image that the deep learning model is focusing on to make the prediction.
The deep learning model predicted the image to be of class '{predicted_class}' with a confidence of {confidence * 100:.2f}%.

In your response:
- Explain what regions of the brain the model is focusing on, based on the saliency map. Refer to the regions highlighted in the light cyan, those are the regions where the model is focusing on.
- Don't mention anything like "The saliency map highlights the regions the model is focusing on, which are in light cyan" in your explanation.
- Keep your explanation to 4 sentences max.
- In case the model prediction is no tumor, verify whether the image is related to an MRI scan of a brain or not. If not, just give a short explanation.
Let's think step by step about this. Verify step by step.
"""


def is_configured() -> bool:
    return bool(GEMINI_API_KEY)


def _ensure_model():
    global _genai, _model
    if _model is not None:
        return _model
    if not GEMINI_API_KEY:
        raise RuntimeError("GEMINI_API_KEY (or GOOGLE_API_KEY) is not set")
    import google.generativeai as genai  # noqa: WPS433

    genai.configure(api_key=GEMINI_API_KEY)
    _genai = genai
    _model = genai.GenerativeModel(model_name=GEMINI_MODEL)
    return _model


@dataclass
class ExplanationResult:
    text: str
    stub: bool


def explain(predicted_class: str, confidence: float, saliency_map_png_b64: str) -> ExplanationResult:
    if not is_configured():
        text = (
            f"(Stub explanation - GEMINI_API_KEY not set on the backend.) "
            f"The model predicts {predicted_class} with {confidence * 100:.1f}% confidence. "
            f"The saliency map highlights the regions that most influenced this prediction."
        )
        return ExplanationResult(text=text, stub=True)

    img_bytes = base64.b64decode(saliency_map_png_b64)
    img = Image.open(io.BytesIO(img_bytes))
    model = _ensure_model()
    prompt = _build_prompt(predicted_class, confidence)
    response = model.generate_content([prompt, img])
    return ExplanationResult(text=response.text or "(no response)", stub=False)
